apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Chart.Name }}-route-http
  namespace: traefik
spec:
  entryPoints:
  - web
  routes:
  - match: Host(`{{ .Values.route.host }}`)
    kind: Rule
    {{- if .Values.route.https.force }}
    middlewares:
    - name: redirect-https-mw
    {{- end }}
    services:
    - kind: Service
      name: {{ .Chart.Name }}-svc
      namespace: {{ .Release.Namespace }}
      port: 80
---
{{- if .Values.route.https.enable }}
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Chart.Name }}-route-https
  namespace: traefik
spec:
  entryPoints:
  - websecure
  routes:
  - match: Host(`{{ .Values.route.host }}`)
    kind: Rule
    middlewares:
    - name: compress-mw
    services:
    - name: {{ .Chart.Name }}-svc
      namespace: {{ .Release.Namespace }}
      port: 80
  tls:
    secretName: {{ .Values.route.https.secretName }}
    options:
      name: {{ .Values.route.https.optionName }}
{{- end }}