apiVersion: v1
kind: Service
metadata:
  name: {{ include "prin.name" . }}-svc
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    {{- include "prin.labels" . | nindent 4 }}
  ports:
  - port: 80
    targetPort: 8980